packages:
  - .

allowBuilds:
  core-js-pure: false
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - "@types/node@22.20.0"
  - '@cloudflare/workerd-darwin-64@1.20260925.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260925.1'
  - '@cloudflare/workerd-linux-64@1.20260925.1'
  - '@cloudflare/workerd-linux-arm64@1.20260925.1'
  - '@cloudflare/workerd-windows-64@1.20260925.1'
  - miniflare@5.20260925.0-alpha
  - workerd@1.20260925.1
  - wrangler@4.141.0
  - '@cloudflare/vite-plugin@1.60.2'
