/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as HymnsIndexRouteImport } from './routes/hymns/index'
import { Route as TemplatesNewRouteImport } from './routes/templates/new'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates/$templateId'
import { Route as TeamsNewRouteImport } from './routes/teams/new'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as OrdersNewRouteImport } from './routes/orders/new'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as MembersNewRouteImport } from './routes/members/new'
import { Route as MembersMemberIdRouteImport } from './routes/members/$memberId'
import { Route as HymnsNewRouteImport } from './routes/hymns/new'
import { Route as HymnsHymnIdRouteImport } from './routes/hymns/$hymnId'

const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const HymnsIndexRoute = HymnsIndexRouteImport.update({
  id: '/hymns/',
  path: '/hymns/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesNewRoute = TemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsNewRoute = TeamsNewRouteImport.update({
  id: '/teams/new',
  path: '/teams/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersNewRoute = MembersNewRouteImport.update({
  id: '/members/new',
  path: '/members/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const HymnsNewRoute = HymnsNewRouteImport.update({
  id: '/hymns/new',
  path: '/hymns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HymnsHymnIdRoute = HymnsHymnIdRouteImport.update({
  id: '/hymns/$hymnId',
  path: '/hymns/$hymnId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/planner': typeof PlannerRoute
  '/hymns/$hymnId': typeof HymnsHymnIdRoute
  '/hymns/new': typeof HymnsNewRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/new': typeof MembersNewRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/teams/new': typeof TeamsNewRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/hymns/': typeof HymnsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/planner': typeof PlannerRoute
  '/hymns/$hymnId': typeof HymnsHymnIdRoute
  '/hymns/new': typeof HymnsNewRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/new': typeof MembersNewRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/teams/new': typeof TeamsNewRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/hymns': typeof HymnsIndexRoute
  '/members': typeof MembersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/planner': typeof PlannerRoute
  '/hymns/$hymnId': typeof HymnsHymnIdRoute
  '/hymns/new': typeof HymnsNewRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/new': typeof MembersNewRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/teams/new': typeof TeamsNewRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/hymns/': typeof HymnsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/planner'
    | '/hymns/$hymnId'
    | '/hymns/new'
    | '/members/$memberId'
    | '/members/new'
    | '/orders/$orderId'
    | '/orders/new'
    | '/teams/$teamId'
    | '/teams/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/hymns/'
    | '/members/'
    | '/settings/'
    | '/teams/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/planner'
    | '/hymns/$hymnId'
    | '/hymns/new'
    | '/members/$memberId'
    | '/members/new'
    | '/orders/$orderId'
    | '/orders/new'
    | '/teams/$teamId'
    | '/teams/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/hymns'
    | '/members'
    | '/settings'
    | '/teams'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/planner'
    | '/hymns/$hymnId'
    | '/hymns/new'
    | '/members/$memberId'
    | '/members/new'
    | '/orders/$orderId'
    | '/orders/new'
    | '/teams/$teamId'
    | '/teams/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/hymns/'
    | '/members/'
    | '/settings/'
    | '/teams/'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlannerRoute: typeof PlannerRoute
  HymnsHymnIdRoute: typeof HymnsHymnIdRoute
  HymnsNewRoute: typeof HymnsNewRoute
  MembersMemberIdRoute: typeof MembersMemberIdRoute
  MembersNewRoute: typeof MembersNewRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  TeamsNewRoute: typeof TeamsNewRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  TemplatesNewRoute: typeof TemplatesNewRoute
  HymnsIndexRoute: typeof HymnsIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hymns/': {
      id: '/hymns/'
      path: '/hymns'
      fullPath: '/hymns/'
      preLoaderRoute: typeof HymnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/new': {
      id: '/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof TemplatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/new': {
      id: '/teams/new'
      path: '/teams/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof TeamsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/new': {
      id: '/members/new'
      path: '/members/new'
      fullPath: '/members/new'
      preLoaderRoute: typeof MembersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hymns/new': {
      id: '/hymns/new'
      path: '/hymns/new'
      fullPath: '/hymns/new'
      preLoaderRoute: typeof HymnsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hymns/$hymnId': {
      id: '/hymns/$hymnId'
      path: '/hymns/$hymnId'
      fullPath: '/hymns/$hymnId'
      preLoaderRoute: typeof HymnsHymnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlannerRoute: PlannerRoute,
  HymnsHymnIdRoute: HymnsHymnIdRoute,
  HymnsNewRoute: HymnsNewRoute,
  MembersMemberIdRoute: MembersMemberIdRoute,
  MembersNewRoute: MembersNewRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersNewRoute: OrdersNewRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  TeamsNewRoute: TeamsNewRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  TemplatesNewRoute: TemplatesNewRoute,
  HymnsIndexRoute: HymnsIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
